services:
  service:
    image: hurlspring:latest
    environment:
      - 'SERVER_PORT=8000'
    ports:
      - '8000:8000'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5433:5432"
