[licenses]
default = "deny"
unlicensed = "deny"
copyleft = "deny"
allow = ["MIT", "Unicode-DFS-2016", "Apache-2.0", "BSD-3-Clause", "ISC", "OpenSSL", "Unlicense", "Zlib", "MPL-2.0"]
private = { ignore = true }

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
allow-git = []

[bans]
multiple-versions = "allow"