set dotenv-load
import 'api_tests/hurl.just'

image_name := "hurl-rocket:latest"


export ROCKET_PORT := "8090"
export SERVER_PORT := "8090"
export AUTH_HS256_SECRET := "CTRKew35ltwdWhGv9WF10lJ06oYBZKzACYhANx7QXPZpvBvCNZbq161xHg2rKhcp"
export AUTH_JWT_AUD := "local.my_domain.com"

@_list:
	just --list --unsorted

# Perform all verifications (compile, test, lint, etc.)
@verify: test lint api_tests
    echo ------------ verify done! ------------  

@sh:
    ./api_tests.sh

run *args:
    cargo run -q -- {{args}}

# Watch the source files and run `just verify` when source changes
watch:
	cargo watch -- just run

# Run tests    
test:
    cargo test

# Run the static code analysis
lint:
    cargo fmt --all -- --check
    cargo clippy

# Clean up compilation output
clean:
	rm -rf target
	rm -rf node_modules


# Build docker image for testing
build:
	docker build -t {{image_name}} .


# Install cargo dev-tools used by the `verify` recipe (requires rustup to be already installed)
install-dev-tools:
	rustup install stable
	rustup override set stable
	cargo install cargo-hack cargo-watch cargo-deny hurl cargo-machete
	cargo install cargo-features-manager


install-hurl:
	curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl_4.1.0_amd64.deb
	udo apt update && sudo apt install ./hurl_4.1.0_amd64.deb
	rm hurl_4.1.0_amd64.deb


@replace-token:
	cd token_creation && just replace

prune:
    cargo machete
    cargo features prune
