services:
  service:
    image: hurl-flask:latest
    environment:
      - 'PORT=8002'
      - 'AUTH_HS256_SECRET=CTRKew35ltwdWhGv9WF10lJ06oYBZKzACYhANx7QXPZpvBvCNZbq161xHg2rKhcp'
      - 'AUTH_JWT_AUD=local.my_domain.com'
    ports:
      - '8003:8003'