name: verify gin showcase

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1,hurl@4
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.0
      - run: just verify-gin