name: publish slides

on:
  push:
    branches: [main]
    paths:
      - 'slides/**'
      - 'img/**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:latest
        with:
          args: slides/slides.md -o dist/index.html
        env:
          MARP_USER: root:root
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.