name: verify rocket showcase

on:
  push:
    branches: [ main ]
    paths:
      - '/showcases/rocket'
  pull_request:
    paths:
      - '/showcases/rocket'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.5,cargo-deny@0.14.20,just@1,hurl@4,cargo-edit@0.12
      - run: just verify-rocket