name: build-and-release

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  _JAVA_OPTS: "-Xmx2g"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.console=plain"

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: gradle
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1,hurl@4
      - run: just verify